### ISSUE TITLE
Image's not loading

### ISSUE THREAD

**Issue by NatSR4** [NatSR4/NatsArtGallery#1]
'Module not found' error even though I've pulled the path to the images directly from the directory and suggestions several times and when following the copied path it still leads to the correct image.

**Comment by Karthik-315** [comment]
Hello, 

I believe when working with Next JS, the `public/` folder is automatically mapped to the root URL (`/`). So try changing the image reference from `../public/Drawings/IMG_3959.JPG` to `/Drawings/IMG_3959.JPG`

Link to the docs: https://nextjs.org/docs/app/building-your-application/optimizing/static-assets

**Comment by NatSR4** [comment]
Oh thanks! I'm seeing this months later. Appreciate the help! I did figure that out when I picked up this project again but I'm only seeing your comment. I fixed this issue so I will be closing it now.

**Comment by NatSR4** [comment]
Next.js automatically picks up images from the public folder, so the path just needed to be modified accordingly.
